config/routes.rb
require 'sidekiq'
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq_web'
  mount RailsAdmin::Engine => '/kasa-admin', as: 'rails_admin'
  resources :properties, only: [:index, :show]

  devise_for :users, :path => '', :path_names => {sign_in: "login", sign_out: "logout", sign_up: "setup", edit: "/account/profile"}, :controllers => {:registrations => "registrations"}

  root 'pages#index'

end

app/models/property.rb
class Property < ActiveRecord::Base
  has_and_belongs_to_many :features
  has_many :images, :dependent => :destroy

  def monetize
    @amount = self.current_list_price.to_i * 100
    @amount = Money.new(@amount, "USD")
    @amount.format
  end

  has_attached_file :featured,
    :storage => :s3,
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
    # :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
    :path => '/:class/:id/:style/:filename',
    # :url => "/system/:attachment/:id/:basename_:style.:extension",
    :url =>':s3_domain_url',

    :styles => {
      :admin    => ['100x100#',  :jpg, :quality => 70],
      :thumb    => ['250x250#',  :jpg, :quality => 70],
      :preview  => ['500x500#',  :jpg, :quality => 70],
      :retina   => ['1920>',     :jpg, :quality => 100]
    },

    :convert_options => {
      :admin    => '-set colorspace sRGB -strip',
      :thumb    => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }

    validates_attachment_content_type :featured, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    process_in_background :featured

    def url
      {:url => ':s3_domain_url'}
    end

    def s3_credentials
      {:bucket => ENV['AWS_BUCKET'], :access_key_id => ENV["access_key_id"], :secret_access_key => ENV["secret_access_key"]}
    end

end

# == Schema Information
#
# Table name: properties
#
#  id                            :integer          not null, primary key
#  mls_listing_number            :string
#  mls_name                      :string
#  mls_sources                   :string
#  mls_date_added                :date
#  mls_date_modified             :date
#  street_number                 :integer
#  street_name                   :string
#  unit_number                   :string
#  city                          :string
#  zip                           :integer
#  location                      :string
#  full_address                  :string
#  property_type                 :string
#  last_update_description       :text
#  short_last_update_description :text
#  status                        :string
#  current_list_price            :decimal(, )
#  sold_price                    :decimal(, )
#  sqft                          :decimal(, )
#  sqft_price                    :decimal(, )
#  lot_sqft                      :decimal(, )
#  year_built                    :integer
#  listing_office                :string
#  condition                     :string
#  bedrooms                      :integer
#  half_bathrooms                :decimal(, )
#  full_bathrooms                :integer
#  favorited                     :integer
#  fake_favorited                :integer
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#  featured_file_name            :string
#  featured_content_type         :string
#  featured_file_size            :integer
#  featured_updated_at           :datetime
#  image_id                      :integer
#  description                   :text
#  short_description             :text
#  garage_size                   :integer
#  has_garage                    :boolean
#
# Indexes
#
#  index_properties_on_full_address  (full_address) UNIQUE
#

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  # before_action :set_images, only: [:show]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @images = @property.images
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save

        if params[:images]
          #===== The magic is here ;)
          params[:images].each { |image|
            @property.images.create(image: image)
          }
        end
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)

        if params[:images]
          #===== The magic is here ;)
          params[:images].each { |image|
            @property.images.create(image: image)
          }
        end

        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def property_params
    params.require(:property).permit(:featured, :description, :short_description, :garage_size, :has_garage, :mls_listing_number, :mls_name, :mls_sources, :mls_date_added, :mls_date_modified, :street_number, :street_name, :unit_number, :city, :zip, :location, :full_address, :property_type, :last_update_description, :short_last_update_description, :status, :current_list_price, :sold_price, :sqft, :sqft_price, :lot_sqft, :year_built, :listing_office, :condition, :bedrooms, :half_bathrooms, :full_bathrooms, :favorited, :fake_favorited)
  end

  # def set_images
  #   0.times {@property.images.build}
  # end
end

app/views/properties/_form.html.haml
= form_for(@property) do |f|
  - if @property.errors.any?
    #error_explanation
      %h2
        = pluralize(@property.errors.count, "error")
        prohibited this property from being saved:
      %ul
        - @property.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :street_number
    %br/
    = f.number_field :street_number
  .field
    = f.label :street_name
    %br/
    = f.text_field :street_name
  .field
    = f.label :unit_number
    %br/
    = f.text_field :unit_number
  .field
    = f.label :city
    %br/
    = f.text_field :city
  .field
    = f.label :zip
    %br/
    = f.number_field :zip
  .field
    = f.label :location
    %br/
    = f.text_field :location
  .field
    = f.label :full_address
    %br/
    = f.text_field :full_address
  .field
    = f.label :property_type
    %br/
    = f.select :property_type, collection: ["Home","Multi-Family","Apartment","Land"]
  .field
    = f.label :short_description
    %br/
    = f.text_area :short_description
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :status
    %br/
    = f.text_field :status
  .field
    = f.label :current_list_price
    %br/
    = f.text_field :current_list_price
  .field
    = f.label :sold_price
    %br/
    = f.text_field :sold_price
  .field
    = f.label :sqft
    %br/
    = f.text_field :sqft
  .field
    = f.label :sqft_price
    %br/
    = f.text_field :sqft_price
  .field
    = f.label :lot_sqft
    %br/
    = f.text_field :lot_sqft
  .field
    = f.label :year_built
    %br/
    = f.number_field :year_built
  .field
    = f.label :listing_office
    %br/
    = f.text_field :listing_office
  .field
    = f.label :condition
    %br/
    = f.text_field :condition
  .field
    = f.label :bedrooms
    %br/
    = f.number_field :bedrooms
  .field
    = f.label :half_bathrooms
    %br/
    = f.text_field :half_bathrooms
  .field
    = f.label :full_bathrooms
    %br/
    = f.number_field :full_bathrooms
  %div
    = f.label :has_garage
    %br/
    = f.check_box :has_garage
    %br/
  :javascript
    $(document).ready(function(){
        $('input[name="property[has_garage]"]').click(function(){
          if($(this).attr("value")=="1"){
          $("#property_garage_size").toggle();
          }
          });
        });
  #property_garage_size.field{:style => "display:none;"}
    = f.label :garage_size
    %br/
    = f.number_field :garage_size
  .field
    = f.label :favorited
    %br/
    = f.number_field :favorited
  .field
    = f.label :fake_favorited
    %br/
    = f.number_field :fake_favorited
  .field
    = f.label :featured
    %br/
    = f.file_field :featured
  %br/
  %p
    tu madre
  = file_field_tag "images[]", type: :file, multiple: true
  .actions
    = f.submit

app/views/properties/edit.html.haml
%h1 Editing Property
= render 'form'
= link_to 'Show', @property
|
= link_to 'Back', properties_path

app/views/properties/index.html.haml
- navigation render 'navigation/interior'
- body_class 'property-listing'
%p#notice= notice
.container-fluid
  .row.pr-25
    .col-sm-12.col-md-12
      %form.form-inline
        .form-group.ml-6em
          %input#exampleInputName2.form-control{:placeholder => "Address, City, or Zip", :type => "text"}/
        .form-group.ml-1-5em
          %label{:for => "exampleInputEmail2"}
            %i.fa.fa-usd.fa-size
          %select.form-control
            %option Any Price
            %option 2
            %option 3
            %option 4
            %option 5
        .form-group.ml-1-5em
          %label{:for => "exampleInputEmail2"}
            = image_tag("bedroom-icon.png", class: "mr-5")
          %select.form-control
            %option All
            %option 2
            %option 3
            %option 4
            %option 5
        .form-group.ml-1-5em
          %label{:for => "exampleInputEmail2"}
            = image_tag("icon-bathroom.png", class: "mr-5")
          %select.form-control
            %option All
            %option 2
            %option 3
            %option 4
            %option 5
        .form-group.ml-1-5em.mt-5
          %label{:for => "exampleInputEmail2"}
            = image_tag("icon-presets.png", class: "mr-5")
            More Filter
        .form-group.pull-right
          %label{:for => "exampleInputEmail2"}
            = image_tag("icon-list-view.png", class: "mr-5")
            List view
  .row.pt-25
    .col-sm-7
      = image_tag("googlemaps-template.jpg", class: "img-responsive")
    .col-sm-5
      .row.pb-20
        .col-sm-7
          .form-group
            %p.pull-left.sort-by
              Sort By:
            %select.form-control.pull-left.sort-by-select
              %option All
              %option Price - High to Low
              %option Price - Low to High
        .col-sm-5.pull-left.text-right
          %p.pr-25.mt-5
            = Property.all.count
            Properties
      - Property.all.each do |prop|
        .row.pb-20
          .col-sm-7
            = image_tag("house.jpg", class: "img-responsive")
          .col-sm-5
            %p
              Bedrooms
              = prop.bedrooms
            %p
              = prop.sqft
            %h4
              %b= prop.monetize

app/views/properties/new.html.haml
%h1 New Property
= render 'form'
= link_to 'Back', properties_path

app/views/properties/show.html.haml
- navigation render 'navigation/interior'
- body_class 'property-show-page'
/ <p id="notice"><haml_loud> notice </haml_loud></p>
%section.full-address
  .contianer-fluid
    .row
      .col-sm-10.col-sm-offset-1
        %h3
          = @property.street_number
          = @property.street_name
          , #{@property.city}, FL #{@property.zip}
.container-fluid
  .row
    .col-sm-12{:style => "padding:0;"}
      .owl-carousel
        - @property.images.each do |img|
          = image_tag img.image(:original), class: "item img-responsive"
:javascript
  $(".owl-carousel").owlCarousel({
      afterUpdate: function () {
          updateSize();
      },
      afterInit:function(){
          updateSize();
      },
      items: 3,
      center: true,
      navRewind:true,
      loop:true,
      margin:0,
      nav:true,
      navText:["<i class='fa fa-angle-left fa-5x'></i>","<i class='fa fa-angle-right fa-5x'></i>"]
  });
  function updateSize(){
      var minHeight=parseInt($('.owl-item').eq(0).css('height'));
      $('.owl-item').each(function () {
          var thisHeight = parseInt($(this).css('height'));
          minHeight=(minHeight<=thisHeight?minHeight:thisHeight);
      });
      $('.owl-wrapper-outer').css('height',minHeight+'px');
  }
%section.property-info
  .container-fluid
    .row
      .col-sm-10.col-sm-offset-1
        .col-sm-8
          .address
            %h2
              = @property.full_address
              - unless @property.unit_number.blank?
                , Unit##{@property.unit_number}
              %br/
              = @property.city
              , FL #{@property.zip}
          .property-description
            %p= raw @property.description
        .col-sm-4
          .property-box
            .property-type
              %p
                %span Property type:
                %span.the-property
                  %i.fa.fa-home.fa-1_5x
                  = @property.property_type
            .property-features
              .features
                %ul
                  %li
                    %img.first{:alt => "Bedrooms", :src => "https://s3-us-west-2.amazonaws.com/kasa-dev/images/property-icons/bedroom.png"}/
                    = @property.bedrooms
                  %li
                    %img{:alt => "Bathroom", :src => "https://s3-us-west-2.amazonaws.com/kasa-dev/images/property-icons/bathroom.png"}/
                    = @property.full_bathrooms
                    = @property.half_bathrooms
                  - unless @property.has_garage == false
                    %li
                      %img{:alt => "Garage", :src => "https://s3-us-west-2.amazonaws.com/kasa-dev/images/property-icons/garage.png"}/
                      = @property.garage_size
            .more-info
              %p
                %b Other Features:
              %p
                Built #{@property.year_built}
                - @property.features.each do |f|
                  , #{f.name}
              %p
                %a.k-blue.mr-15{:href => "#"} Favorite
                %a.k-blue{:href => "#"} Share
              %hr/
              .row
                .col-md-8
                  %h2= number_to_currency(@property.current_list_price, :unit => "$")
                  %p.sqft-price
                    = number_to_currency((@property.current_list_price/@property.sqft), :unit => "$", :precision => 0)
                    \/sf
                .col-md-4
                  %p.status.mt-15
                    %b= @property.status
                  %p.mt-15
                    %b
                      = ((Time.zone.now - @property.created_at) / 3600).to_i.round
                      hrs ago
            .mt-10
            .row
              .col-sm-12
                %a.create-an-offer{:href => "#"} CREATE AN OFFER
            .mt-10
            .row
              .col-sm-12
                %a.request-showing{:href => "#"} REQUEST SHOWING
            .mt-10
            .row
              .col-sm-12
                %a.request-info{:href => "#"} Request More Info
            .mt-20
            .row
              .col-sm-12
                %p.learn-more
                  Get a
                  %b $6,475
                  refund when you buy with KASA.
                  %a.k-blue{:href => "#"} Learn more
|
= link_to 'Back', properties_path